import type { CSSProperties } from "react";
import { SEM, soft, T } from "./theme";

export const mono = `var(--font-mono, ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace)`;
export const sans = `var(--font-sans, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif)`;

/** Every inline style for the devtools UI, in one place. Colors come from the
 * host app's CSS variables via ./theme so the panel matches the app's palette. */
export const S = {
  root: {
    position: "fixed",
    bottom: 20,
    zIndex: 2147483000,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    fontFamily: sans,
  },
  fab: {
    width: 44,
    height: 44,
    borderRadius: 22,
    border: "none",
    cursor: "pointer",
    display: "grid",
    placeItems: "center",
    position: "relative",
    background: T.primary,
    color: T.primaryFg,
    boxShadow: `0 8px 24px ${soft(T.primary, 45)}`,
    transition: "transform .15s ease",
  },
  fabOpen: { background: T.card, color: T.fg, boxShadow: "0 8px 20px rgba(0,0,0,.4)" },
  fabBadge: {
    position: "absolute",
    top: -3,
    right: -3,
    minWidth: 16,
    height: 16,
    padding: "0 5px",
    borderRadius: 8,
    background: T.danger,
    color: "#fff",
    fontSize: 10,
    fontWeight: 700,
    display: "grid",
    placeItems: "center",
    boxShadow: `0 0 0 2px ${T.surface}`,
  },
  panel: {
    position: "relative",
    maxWidth: "calc(100vw - 40px)",
    maxHeight: "calc(100vh - 120px)",
    display: "flex",
    flexDirection: "column",
    background: T.surface,
    border: `1px solid ${T.border}`,
    borderRadius: 16,
    boxShadow: "0 24px 64px rgba(0,0,0,.45)",
    overflow: "hidden",
    color: T.fg,
  },
  tail: {
    position: "absolute",
    bottom: -8,
    width: 18,
    height: 18,
    background: T.surface,
    borderRight: `1px solid ${T.border}`,
    borderBottom: `1px solid ${T.border}`,
    transform: "rotate(45deg)",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    borderBottom: `1px solid ${T.border}`,
  },
  title: { fontSize: 13, fontWeight: 700, lineHeight: 1.2 },
  subtitle: { fontSize: 11, color: T.muted, marginTop: 2 },
  tabs: { display: "flex", gap: 4, padding: "8px 10px", borderBottom: `1px solid ${T.border}` },
  tab: {
    flex: 1,
    padding: "7px 10px",
    borderRadius: 9,
    border: "none",
    background: "transparent",
    color: T.muted,
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: sans,
  },
  tabActive: { background: soft(T.fg, 8), color: T.fg },
  body: { flex: 1, minHeight: 0, display: "flex", flexDirection: "column" },
  scroll: { flex: 1, overflowY: "auto", padding: 10, display: "flex", flexDirection: "column", gap: 8 },

  // state rows
  atomRow: {
    textAlign: "left",
    background: "transparent",
    border: `1px solid ${T.border}`,
    borderRadius: 11,
    padding: "9px 11px",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontFamily: sans,
    transition: "background .12s",
  },
  atomTop: { display: "flex", alignItems: "center", gap: 8 },
  atomName: { fontSize: 12.5, fontWeight: 600, color: T.fg, fontFamily: mono, flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  atomValue: {
    fontFamily: mono,
    fontSize: 11.5,
    color: T.code,
    lineHeight: 1.5,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    wordBreak: "break-word",
  },
  atomValueOpen: { WebkitLineClamp: "unset", display: "block", whiteSpace: "pre-wrap" },

  // pills/chips
  pill: { display: "inline-flex", alignItems: "center", gap: 5, padding: "2px 8px", borderRadius: 20, fontSize: 10.5, fontWeight: 600 },
  pillDot: { width: 6, height: 6, borderRadius: 3 },
  changeChip: { fontSize: 10.5, fontWeight: 700, color: T.primary, background: soft(T.primary, 14), padding: "2px 7px", borderRadius: 20 },
  actionChip: { fontSize: 10.5, fontWeight: 700, color: SEM.violet, background: soft(SEM.violet, 16), padding: "2px 7px", borderRadius: 20 },
  disposedChip: { fontSize: 10, fontWeight: 700, color: T.muted, background: soft(T.muted, 16), padding: "2px 7px", borderRadius: 20 },

  // chat
  msg: { display: "flex", gap: 9, alignItems: "flex-start" },
  avatar: { width: 28, height: 28, borderRadius: 9, display: "grid", placeItems: "center", fontSize: 12, fontWeight: 700, flexShrink: 0, fontFamily: mono },
  msgHead: { display: "flex", alignItems: "center", gap: 7, marginBottom: 3 },
  msgLabel: { fontSize: 12, fontWeight: 600, fontFamily: mono, color: T.fg, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", maxWidth: 150 },
  kindTag: { fontSize: 9.5, fontWeight: 700, padding: "1px 6px", borderRadius: 6, textTransform: "uppercase", letterSpacing: ".03em" },
  msgTime: { fontSize: 10, color: T.faint, marginLeft: "auto", flexShrink: 0, fontFamily: mono },
  bubble: { background: soft(T.fg, 4), border: "1px solid", borderRadius: "4px 12px 12px 12px", padding: "7px 10px", fontSize: 11.5, lineHeight: 1.5, wordBreak: "break-word" },
  detail: { fontSize: 10, color: T.faint, marginTop: 4, fontFamily: mono },
  prevVal: { fontFamily: mono, color: T.faint, textDecoration: "line-through", opacity: 0.85 },
  nextVal: { fontFamily: mono, color: T.code },
  errVal: { fontFamily: mono, color: T.danger },
  arrow: { color: T.faint },

  empty: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", color: T.muted, fontSize: 13, textAlign: "center", padding: 24 },
  emptyHint: { fontSize: 11.5, color: T.faint, marginTop: 6, maxWidth: 240, lineHeight: 1.5 },

  iconBtn: { width: 30, height: 30, borderRadius: 8, border: "none", background: "transparent", color: T.muted, cursor: "pointer", display: "grid", placeItems: "center", transition: "all .12s" },
} satisfies Record<string, CSSProperties>;
